### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ramyc46** [farseeker/go-mikrotik-rif#1]
I cannot run mikrotik-rif-windows.exe in windows 7x64

**Comment by ramyc46** [comment]
> 
> 
> I cannot run mikrotik-rif-windows.exe in windows 7x64

**Comment by mhenderson-so** [comment]
Can you be more specific? I don't have a Windows 7 machine handy. Screenshots? Error messages?

**Comment by ramyc46** [comment]
Dear
I have attached a video file showing the problem
And I have attached a (.rif) file that I would like to modify it, replace number 1 by
number 3
if you please

________________________________
من: Mark Henderson <notifications@github.com>
‏‏تم الإرسال: 12/شعبان/1440 10:02 م
إلى: farseeker/go-mikrotik-rif
نسخة: ramyc46; State change
‏‏الموضوع: Re: [farseeker/go-mikrotik-rif] help (#1)


Can you be more specific? I don't have a Windows 7 machine handy. Screenshots? Error messages?

**Comment by farseeker** [comment]
I'm afraid attachments don't work on GitHub Issues. Can you upload the video or a screenshot somewhere for me to look at?

**Comment by ramyc46** [comment]
http://www.mediafire.com/folder/i5i1114gd7i71/1
[https://www.mediafire.com/images/logos/mf_logo250x250.png]<http://www.mediafire.com/folder/i5i1114gd7i71/1>

MediaFire<http://www.mediafire.com/folder/i5i1114gd7i71/1>
MediaFire is a simple to use free service that lets you put all your photos, documents, music, and video in a single place so you can access them anywhere and share them everywhere.
www.mediafire.com



________________________________
من: Mark Henderson <notifications@github.com>
‏‏تم الإرسال: 14/شعبان/1440 10:15 م
إلى: farseeker/go-mikrotik-rif
نسخة: ramyc46; State change
‏‏الموضوع: Re: [farseeker/go-mikrotik-rif] help (#1)


I'm afraid attachments don't work on GitHub Issues. Can you upload the video or a screenshot somewhere for me to look at?

**Comment by farseeker** [comment]
Thanks for the video - that helps a lot.

This is a console application, which means that it's meant to be run from the command line. If you open a command prompt, `cd` to where you have downloaded the program (it appears to be in \temp, so you would type `cd \temp`, and then run `mikrotik-rif-windows.exe supout.rif` (or whatever your `.rif` is called) the output will be put onto the screen.

If you want to save the output, you can pipe it into a text file. For example, `mikrotik-rif-windows.exe supout.rif > supout.txt` - that will give you a text file called `supout.txt` with the decoded RIF file.

**Comment by ramyc46** [comment]
thank you very much for your help
can I  modify  the file(supout.txt)and re encrypt it as mentioned in the program help
Regards

________________________________
من: Mark Henderson <notifications@github.com>
‏‏تم الإرسال: 15/شعبان/1440 08:54 م
إلى: farseeker/go-mikrotik-rif
نسخة: ramyc46; State change
‏‏الموضوع: Re: [farseeker/go-mikrotik-rif] help (#1)


Thanks for the video - that helps a lot.

This is a console application, which means that it's meant to be run from the command line. If you open a command prompt, cd to where you have downloaded the program, and then run mikrotik-rif-windows.exe supout.rif (or whatever your .rif is called) the output will be put onto the screen.

If you want to save the output, you can pipe it into a text file. For example, mikrotik-rif-windows.exe supout.rif > supout.txt - that will give you a text file called supout.txt with the decoded RIF file.

**Comment by ramyc46** [comment]
It is works see attached file
________________________________
من: Osama hammady <osamahammady@hotmail.com>
‏‏تم الإرسال: 16/شعبان/1440 12:50 م
إلى: farseeker/go-mikrotik-rif
‏‏الموضوع: رد: [farseeker/go-mikrotik-rif] help (#1)

thank you very much for your help
can I  modify  the file(supout.txt)and re encrypt it as mentioned in the program help
Regards

________________________________
من: Mark Henderson <notifications@github.com>
‏‏تم الإرسال: 15/شعبان/1440 08:54 م
إلى: farseeker/go-mikrotik-rif
نسخة: ramyc46; State change
‏‏الموضوع: Re: [farseeker/go-mikrotik-rif] help (#1)


Thanks for the video - that helps a lot.

This is a console application, which means that it's meant to be run from the command line. If you open a command prompt, cd to where you have downloaded the program, and then run mikrotik-rif-windows.exe supout.rif (or whatever your .rif is called) the output will be put onto the screen.

If you want to save the output, you can pipe it into a text file. For example, mikrotik-rif-windows.exe supout.rif > supout.txt - that will give you a text file called supout.txt with the decoded RIF file.

**Comment by farseeker** [comment]
You cannot re-encode the decoded RIF file using my program. This is a one-way operation. I guess in theory the ability to re-encode a decoded RIF is possible, but I don't see why you would want to modify a RIF before sending it to someone.

**Comment by ramyc46** [comment]
Dear
I have a meny of devices (RouterBoard sxt5nd) from Mikrotik. The price of the device is $ 45 . I lost its license and when I applied for a new license the price was very expensive.
They have on-site a service to get a demo license
I would like to convert the demo license to full license
best regards
________________________________
من: Mark Henderson <notifications@github.com>
‏‏تم الإرسال: 16/شعبان/1440 10:55 م
إلى: farseeker/go-mikrotik-rif
نسخة: ramyc46; State change
‏‏الموضوع: Re: [farseeker/go-mikrotik-rif] help (#1)


You cannot re-encode the decoded RIF file using my program. This is a one-way operation. I guess in theory the ability to re-encode a decoded RIF is possible, but I don't see why you would want to modify a RIF before sending it to someone.
