### ISSUE TITLE
Release for MacOs X

### ISSUE THREAD

**Issue by diegotibi** [farseeker/go-mikrotik-rif#2]
Hi,
I've build the release for MacOsX. 
[mikrotik-rif-osx.zip](https://github.com/farseeker/go-mikrotik-rif/files/4292592/mikrotik-rif-osx.zip)

**Comment by mhenderson-so** [comment]
Thanks. I have renamed it to `mikrotik-rif-darwin` in keeping with Go's `GOOS` settings and provided it in releases! I'll also cross-compile for OSX in the future if I ever make any revisions.
