### ISSUE TITLE
Antivirus detection

### ISSUE THREAD

**Issue by erfan-azhdari** [farseeker/go-mikrotik-rif#3]
Windows Defender detects the latest release files as Trojan:Win32/Casdet!rfn

Photo:
![image](https://user-images.githubusercontent.com/32454197/80358403-9898af00-8891-11ea-81cf-b665218d7c13.png)

**Comment by mhenderson-t2** [comment]
This is very odd - I can also reproduce this at my end on the binaries on the release page.

I have re-compiled using the latest version of Go and that appears to have fixed the issue. I have re-uploaded them against the GitHub releases, so if you try the download again you should be OK.

**Comment by erfan-azhdari** [comment]
thx. fixed now
